from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import css


class UiForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(310, 560)
        Form.setMinimumSize(QtCore.QSize(310, 0))
        Form.setMaximumSize(QtCore.QSize(310, 560))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_ac = QtWidgets.QPushButton(Form)
        self.btn_ac.setGeometry(QtCore.QRect(20, 200, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ac.setFont(font)
        self.btn_ac.setStyleSheet(css.regular)
        self.btn_ac.setObjectName("btn_ac")
        self.btn_back = QtWidgets.QPushButton(Form)
        self.btn_back.setGeometry(QtCore.QRect(90, 200, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet(css.regular)
        self.btn_back.setObjectName("btn_back")
        self.btn_7 = QtWidgets.QPushButton(Form)
        self.btn_7.setGeometry(QtCore.QRect(20, 270, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet(css.regular)
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(Form)
        self.btn_8.setGeometry(QtCore.QRect(90, 270, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet(css.regular)
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(Form)
        self.btn_9.setGeometry(QtCore.QRect(160, 270, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet(css.regular)
        self.btn_9.setObjectName("btn_9")
        self.btn_6 = QtWidgets.QPushButton(Form)
        self.btn_6.setGeometry(QtCore.QRect(160, 340, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet(css.regular)
        self.btn_6.setObjectName("btn_6")
        self.btn_5 = QtWidgets.QPushButton(Form)
        self.btn_5.setGeometry(QtCore.QRect(90, 340, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet(css.regular)
        self.btn_5.setObjectName("btn_5")
        self.btn_4 = QtWidgets.QPushButton(Form)
        self.btn_4.setGeometry(QtCore.QRect(20, 340, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet(css.regular)
        self.btn_4.setObjectName("btn_4")
        self.btn_3 = QtWidgets.QPushButton(Form)
        self.btn_3.setGeometry(QtCore.QRect(160, 410, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet(css.regular)
        self.btn_3.setObjectName("btn_3")
        self.btn_1 = QtWidgets.QPushButton(Form)
        self.btn_1.setGeometry(QtCore.QRect(20, 410, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet(css.regular)
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(Form)
        self.btn_2.setGeometry(QtCore.QRect(90, 410, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet(css.regular)
        self.btn_2.setObjectName("btn_2")
        self.btn_0 = QtWidgets.QPushButton(Form)
        self.btn_0.setGeometry(QtCore.QRect(20, 480, 130, 62))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet(css.regular)
        self.btn_0.setObjectName("btn_0")
        self.btn_dot = QtWidgets.QPushButton(Form)
        self.btn_dot.setGeometry(QtCore.QRect(160, 480, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dot.setFont(font)
        self.btn_dot.setStyleSheet(css.regular)
        self.btn_dot.setObjectName("btn_dot")
        self.btn_divide = QtWidgets.QPushButton(Form)
        self.btn_divide.setGeometry(QtCore.QRect(160, 200, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_divide.setFont(font)
        self.btn_divide.setStyleSheet(css.functions)
        self.btn_divide.setObjectName("btn_divide")
        self.btn_multiply = QtWidgets.QPushButton(Form)
        self.btn_multiply.setGeometry(QtCore.QRect(230, 200, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_multiply.setFont(font)
        self.btn_multiply.setStyleSheet(css.functions)
        self.btn_multiply.setObjectName("btn_multiply")
        self.btn_subtract = QtWidgets.QPushButton(Form)
        self.btn_subtract.setGeometry(QtCore.QRect(230, 270, 62, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_subtract.setFont(font)
        self.btn_subtract.setStyleSheet(css.functions)
        self.btn_subtract.setObjectName("btn_subtract")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(230, 340, 62, 90))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet(css.functions)
        self.btn_add.setObjectName("btn_add")
        self.btn_equal = QtWidgets.QPushButton(Form)
        self.btn_equal.setGeometry(QtCore.QRect(230, 440, 62, 100))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet(css.equal)
        self.btn_equal.setObjectName("btn_equal")
        self.math_label = QtWidgets.QLabel(Form)
        self.math_label.setGeometry(QtCore.QRect(20, 80, 271, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.math_label.setFont(font)
        self.math_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.math_label.setStyleSheet("color: rgb(138, 138, 138);")
        self.math_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.math_label.setObjectName("math_label")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 120, 271, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.space_label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.space_label_2.setFont(font)
        self.space_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.space_label_2.setStyleSheet("color: rgb(66, 66, 66);\n"
                                        "text-align:right;")
        self.space_label_2.setText("")
        self.space_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.space_label_2.setObjectName("space_label_2")
        self.horizontalLayout.addWidget(self.space_label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.result_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.result_label.setFont(font)
        self.result_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.result_label.setStyleSheet("color: rgb(66, 66, 66);")
        self.result_label.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignLeft)
        self.result_label.setObjectName("result_label")
        self.horizontalLayout.addWidget(self.result_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Buttons call
        self.btn_ac.clicked.connect(lambda: self.clear())
        self.btn_back.clicked.connect(lambda: self.backspace())
        self.btn_equal.clicked.connect(lambda: self.calculate())
        self.btn_dot.clicked.connect(lambda: self.add("."))
        self.btn_divide.clicked.connect(lambda: self.add("/"))
        self.btn_multiply.clicked.connect(lambda: self.add("*"))
        self.btn_subtract.clicked.connect(lambda: self.add("-"))
        self.btn_add.clicked.connect(lambda: self.add("+"))
        self.btn_1.clicked.connect(lambda: self.add("1"))
        self.btn_2.clicked.connect(lambda: self.add("2"))
        self.btn_3.clicked.connect(lambda: self.add("3"))
        self.btn_4.clicked.connect(lambda: self.add("4"))
        self.btn_5.clicked.connect(lambda: self.add("5"))
        self.btn_6.clicked.connect(lambda: self.add("6"))
        self.btn_7.clicked.connect(lambda: self.add("7"))
        self.btn_8.clicked.connect(lambda: self.add("8"))
        self.btn_9.clicked.connect(lambda: self.add("9"))
        self.btn_0.clicked.connect(lambda: self.add("0"))

    # App functions
    def add(self, text):
        expression = self.math_label.text()
        expression += text
        self.math_label.setText(expression)

    def clear(self):
        self.math_label.setText("")
        self.result_label.setText("0")

    def backspace(self):
        expression = self.math_label.text()
        expression = expression[:-1]
        self.math_label.setText(expression)

    def calculate(self):
        result = ""
        expression = self.math_label.text()
        if expression == "":
                return
        if expression != "":
                try:
                        result = eval(expression)
                        expression = str(result)
                except:
                        result = "Error"
                        self.result_label.setText(str(result))
                        return
        rounded_number = round(result, 2)
        self.result_label.setText(str(rounded_number))
        # self.math_label.setText(str(rounded_number))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Qt Calculator"))
        Form.setWindowIcon(QIcon("files/app_icon.png"))
        self.btn_ac.setText(_translate("Form", "C"))
        self.btn_back.setText(_translate("Form", "⌫"))
        self.btn_7.setText(_translate("Form", "7"))
        self.btn_8.setText(_translate("Form", "8"))
        self.btn_9.setText(_translate("Form", "9"))
        self.btn_6.setText(_translate("Form", "6"))
        self.btn_5.setText(_translate("Form", "5"))
        self.btn_4.setText(_translate("Form", "4"))
        self.btn_3.setText(_translate("Form", "3"))
        self.btn_1.setText(_translate("Form", "1"))
        self.btn_2.setText(_translate("Form", "2"))
        self.btn_0.setText(_translate("Form", "0"))
        self.btn_dot.setText(_translate("Form", "."))
        self.btn_divide.setText(_translate("Form", "/"))
        self.btn_multiply.setText(_translate("Form", "*"))
        self.btn_multiply.setProperty("class", _translate("Form", "btn_style1"))
        self.btn_subtract.setText(_translate("Form", "-"))
        self.btn_add.setText(_translate("Form", "+"))
        self.btn_equal.setText(_translate("Form", "="))
        self.math_label.setText(_translate("Form", ""))
        self.result_label.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UiForm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
